#!/bin/bash
set -euo pipefail

sleep 0.2

CNTRY=NL
R="Europe/Amsterdam"

HDD=nvme0n1
DISK="/dev/$HDD"
EX=p
CR=crt

SIZE1=500M
SIZE2=80G

#sgdisk -Z $DISK

#sgdisk -n 1::+$SIZE1 -t 1:EF00 -c 1:"EFI" $DISK
#sgdisk -n 2::+$SIZE2 -t 2:8300 -c 2:"ROOT" $DISK

echo
echo "🥵💀🥵💀🥵💀🥵💀🥵💀🥵💀🥵💀🥵💀🥵💀🥵💀🥵💀🥵💀"
echo

read -rp "user: " USERNAME
while true; do
    read -rsp "pswd: " PASSWORD
    echo
    read -rsp "pswd: " PASSWORD_CONFIRM
    echo
    if [ "$PASSWORD" = "$PASSWORD_CONFIRM" ]; then
        break
    else
        echo "pswd mismatch"
    fi
done

reflector -c "$CNTRY" -p https --age 4 --latest 15 --save /etc/pacman.d/mirrorlist
sed -i 's/^SigLevel.*/SigLevel = Never/' /etc/pacman.conf
sed -i 's/^LocalFileSigLevel.*/LocalFileSigLevel = Never/' /etc/pacman.conf
sed -i '/^\[options\]/a Color' /etc/pacman.conf

cryptsetup luksFormat --batch-mode ${DISK}${EX}2
cryptsetup luksOpen ${DISK}${EX}2 $CR

mkfs.fat ${DISK}${EX}1
mkfs.ext4 /dev/mapper/$CR

PART_UUID=$(blkid -s UUID -o value "${DISK}${EX}2")

mount /dev/mapper/$CR /mnt
mount -o umask=0077 -m ${DISK}${EX}1 /mnt/boot

fallocate -l 8G /mnt/sf
chmod 600 /mnt/sf
mkswap /mnt/sf
swapon -p 10 /mnt/sf

pacstrap -KP /mnt base

genfstab -U /mnt >> /mnt/etc/fstab

#sudo pacman -S upower
#sudo systemctl enable upower

#+++ Recommendations
#* Install ethtool to disable Wake-on-LAN
#* Install smartmontools for disk drive health info

#sudo systemctl enable --now NetworkManager-dispatcher.service
#sudo systemctl mask systemd-rfkill.service systemd-rfkill.socket
#sudo systemctl enable --now tlp.service

# Add fish to valid shells if needed
#echo /usr/bin/fish | sudo tee -a /etc/shells

# Set as default
#chsh -s /usr/bin/fish

#alias is='sudo pacman -S --needed'
#alias ls='eza -la --icons --group-directories-first --sort=size'

#/etc/locale.gen
#locale-gen

#/etc/locale.conf
#LANG=en_US.UTF-8

arch-chroot /mnt bash <<😈
set -e

pacman -S --noconfirm mkinitcpio

sed -i 's/^HOOKS=.*/HOOKS=(base udev autodetect modconf keyboard block encrypt filesystems)/' /etc/mkinitcpio.conf

curl -LO https://github.com/sldll/s/raw/main/pkg
grep -v '^\s*#' pkg | pacman -S --needed --noconfirm -

echo "root:$PASSWORD" | chpasswd

useradd -mG wheel $USERNAME
echo "$USERNAME:$PASSWORD" | chpasswd
echo "%wheel ALL=(ALL) ALL" >> /etc/sudoers

sed -i 's/fmask=0022,dmask=0022/umask=0077/' /etc/fstab
sed -i '/\bext4\b/ s/\brelatime\b/noatime/g' /etc/fstab

bootctl install
echo "title ubuntu" >> /boot/loader/entries/arch.conf
echo "linux /vmlinuz-linux" >> /boot/loader/entries/arch.conf
echo "initrd /intel-ucode.img" >> /boot/loader/entries/arch.conf
echo "initrd /initramfs-linux.img" >> /boot/loader/entries/arch.conf
echo "options cryptdevice=UUID=$PART_UUID:$CR root=/dev/mapper/$CR rw" >> /boot/loader/entries/arch.conf

echo "[zram0]" >> /etc/systemd/zram-generator.conf
echo "zram-size = ram / 2" >> /etc/systemd/zram-generator.conf
echo "compression-algorithm = lz4" >> /etc/systemd/zram-generator.conf
echo "swap-priority = 100" >> /etc/systemd/zram-generator.conf

echo "vm.swappiness=60" >> /etc/sysctl.d/99-swappiness.conf

echo "XDG_CURRENT_DESKTOP=sway" >> /etc/environment

echo "GTK_THEME=Adwaita:dark" >> /etc/environment
echo "QT_QPA_PLATFORMTHEME=gtk3" >> /etc/environment
echo "QT_STYLE_OVERRIDE=adwaita-dark" >> /etc/environment

echo "LENOVO_BAT_CONSERVATION_MODE=1" >> /etc/tlp.conf
echo "START_CHARGE_THRESH_BAT0=75" >> /etc/tlp.conf

echo "ubuntu" >> /etc/hostname

ln -sf /usr/share/zoneinfo/$R /etc/localtime
hwclock --systohc

systemctl enable NetworkManager
systemctl enable fstrim.timer
systemctl enable tlp
systemctl enable tlp-pd

su - $USERNAME -c 'git clone https://github.com/sldll/s dot && cd dot && stow --no-folding --adopt . && git restore .'

echo
echo "🥵💀🥵💀🥵💀🥵💀🥵💀🥵💀🥵💀🥵💀🥵💀🥵💀🥵💀🥵💀"
echo

😈
